/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a nonce and mint its tap URLs
         * @description Called by the machine that wants approval, with a bearer token.
         *     Form-encoded rather than JSON because the caller is a shell
         *     script using `curl -d`, for which form encoding is the natural
         *     shape.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/d/{nonce}/{token}/{verb}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nonce: components["parameters"]["Nonce"];
                /**
                 * @description A single-use capability. It is in the URL, so nothing may log or
                 *     echo the request path - see the note in server.go.
                 */
                token: components["parameters"]["Token"];
                verb: components["parameters"]["Verb"];
            };
            cookie?: never;
        };
        /**
         * The confirmation page a person lands on
         * @description HTML, because the consumer is a thumb on a phone. Renders a
         *     button that POSTs to this same path - a GET must not decide
         *     anything, since link previews and prefetchers issue GETs.
         */
        get: operations["tapConfirm"];
        put?: never;
        /** Record the decision and publish it */
        post: operations["tap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness and liveness */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Registration: {
            approve_url: string;
            deny_url: string;
            expires_in_seconds: number;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        Error: {
            message: string;
        };
    };
    responses: {
        /** @description The request was rejected. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Nonce: string;
        /**
         * @description A single-use capability. It is in the URL, so nothing may log or
         *     echo the request path - see the note in server.go.
         */
        Token: string;
        Verb: "approve" | "deny";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @description Caller's identifier for this request; must be unique while pending. */
                    nonce: string;
                    /** @description Shown to the person deciding. Truncated, control characters stripped. */
                    detail?: string;
                };
            };
        };
        responses: {
            /** @description The nonce was registered and its URLs minted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registration"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            /** @description That nonce is already registered and still pending. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error this operation does not otherwise document. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    tapConfirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nonce: components["parameters"]["Nonce"];
                /**
                 * @description A single-use capability. It is in the URL, so nothing may log or
                 *     echo the request path - see the note in server.go.
                 */
                token: components["parameters"]["Token"];
                verb: components["parameters"]["Verb"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page with a button confirming the decision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description An explanation for a person. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description An explanation for a person. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description An error this operation does not otherwise document. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    tap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nonce: components["parameters"]["Nonce"];
                /**
                 * @description A single-use capability. It is in the URL, so nothing may log or
                 *     echo the request path - see the note in server.go.
                 */
                token: components["parameters"]["Token"];
                verb: components["parameters"]["Verb"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The decision was recorded and published. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description An explanation for a person. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description An explanation for a person. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description An explanation for a person. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description An error this operation does not otherwise document. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description An error this operation does not otherwise document. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
