// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetHealthz implements getHealthz operation.
//
// Readiness and liveness.
//
// GET /healthz
func (UnimplementedHandler) GetHealthz(ctx context.Context) (r *Health, _ error) {
	return r, ht.ErrNotImplemented
}

// Register implements register operation.
//
// Called by the machine that wants approval, with a bearer token. Form-encoded rather than JSON
// because the caller is a shell script using `curl -d`, for which form encoding is the natural shape.
//
// POST /register
func (UnimplementedHandler) Register(ctx context.Context, req *RegisterReq) (r RegisterRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Tap implements tap operation.
//
// Record the decision and publish it.
//
// POST /d/{nonce}/{token}/{verb}
func (UnimplementedHandler) Tap(ctx context.Context, params TapParams) (r TapRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TapConfirm implements tapConfirm operation.
//
// HTML, because the consumer is a thumb on a phone. Renders a button that POSTs to this same path - a
// GET must not decide anything, since link previews and prefetchers issue GETs.
//
// GET /d/{nonce}/{token}/{verb}
func (UnimplementedHandler) TapConfirm(ctx context.Context, params TapConfirmParams) (r TapConfirmRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
