// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetHealthz implements getHealthz operation.
	//
	// Readiness and liveness.
	//
	// GET /healthz
	GetHealthz(ctx context.Context) (*Health, error)
	// Register implements register operation.
	//
	// Called by the machine that wants approval, with a bearer token. Form-encoded rather than JSON
	// because the caller is a shell script using `curl -d`, for which form encoding is the natural shape.
	//
	// POST /register
	Register(ctx context.Context, req *RegisterReq) (RegisterRes, error)
	// Tap implements tap operation.
	//
	// Record the decision and publish it.
	//
	// POST /d/{nonce}/{token}/{verb}
	Tap(ctx context.Context, params TapParams) (TapRes, error)
	// TapConfirm implements tapConfirm operation.
	//
	// HTML, because the consumer is a thumb on a phone. Renders a button that POSTs to this same path - a
	// GET must not decide anything, since link previews and prefetchers issue GETs.
	//
	// GET /d/{nonce}/{token}/{verb}
	TapConfirm(ctx context.Context, params TapConfirmParams) (TapConfirmRes, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
