// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"io"

	"github.com/go-faster/errors"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Error
type Error struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/Health
type Health struct {
	Status HealthStatus `json:"status"`
}

// GetStatus returns the value of Status.
func (s *Health) GetStatus() HealthStatus {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *Health) SetStatus(val HealthStatus) {
	s.Status = val
}

type HealthStatus string

const (
	HealthStatusOk HealthStatus = "ok"
)

// AllValues returns all HealthStatus values.
func (HealthStatus) AllValues() []HealthStatus {
	return []HealthStatus{
		HealthStatusOk,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthStatus) MarshalText() ([]byte, error) {
	switch s {
	case HealthStatusOk:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthStatus) UnmarshalText(data []byte) error {
	switch HealthStatus(data) {
	case HealthStatusOk:
		*s = HealthStatusOk
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type RegisterBadRequest Error

func (*RegisterBadRequest) registerRes() {}

type RegisterConflict Error

func (*RegisterConflict) registerRes() {}

type RegisterReq struct {
	// Caller's identifier for this request; must be unique while pending.
	Nonce string `json:"nonce"`
	// Shown to the person deciding. Truncated, control characters stripped.
	Detail OptString `json:"detail"`
}

// GetNonce returns the value of Nonce.
func (s *RegisterReq) GetNonce() string {
	return s.Nonce
}

// GetDetail returns the value of Detail.
func (s *RegisterReq) GetDetail() OptString {
	return s.Detail
}

// SetNonce sets the value of Nonce.
func (s *RegisterReq) SetNonce(val string) {
	s.Nonce = val
}

// SetDetail sets the value of Detail.
func (s *RegisterReq) SetDetail(val OptString) {
	s.Detail = val
}

type RegisterToken struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *RegisterToken) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *RegisterToken) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *RegisterToken) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *RegisterToken) SetRoles(val []string) {
	s.Roles = val
}

type RegisterUnauthorized Error

func (*RegisterUnauthorized) registerRes() {}

// Ref: #/components/schemas/Registration
type Registration struct {
	ApproveURL       string `json:"approve_url"`
	DenyURL          string `json:"deny_url"`
	ExpiresInSeconds int    `json:"expires_in_seconds"`
}

// GetApproveURL returns the value of ApproveURL.
func (s *Registration) GetApproveURL() string {
	return s.ApproveURL
}

// GetDenyURL returns the value of DenyURL.
func (s *Registration) GetDenyURL() string {
	return s.DenyURL
}

// GetExpiresInSeconds returns the value of ExpiresInSeconds.
func (s *Registration) GetExpiresInSeconds() int {
	return s.ExpiresInSeconds
}

// SetApproveURL sets the value of ApproveURL.
func (s *Registration) SetApproveURL(val string) {
	s.ApproveURL = val
}

// SetDenyURL sets the value of DenyURL.
func (s *Registration) SetDenyURL(val string) {
	s.DenyURL = val
}

// SetExpiresInSeconds sets the value of ExpiresInSeconds.
func (s *Registration) SetExpiresInSeconds(val int) {
	s.ExpiresInSeconds = val
}

func (*Registration) registerRes() {}

type TapBadGateway struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s TapBadGateway) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*TapBadGateway) tapRes() {}

type TapConfirmGone struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s TapConfirmGone) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*TapConfirmGone) tapConfirmRes() {}

type TapConfirmNotFound struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s TapConfirmNotFound) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*TapConfirmNotFound) tapConfirmRes() {}

type TapConfirmOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s TapConfirmOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*TapConfirmOK) tapConfirmRes() {}

type TapGone struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s TapGone) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*TapGone) tapRes() {}

type TapNotFound struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s TapNotFound) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*TapNotFound) tapRes() {}

type TapOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s TapOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*TapOK) tapRes() {}

type Verb string

const (
	VerbApprove Verb = "approve"
	VerbDeny    Verb = "deny"
)

// AllValues returns all Verb values.
func (Verb) AllValues() []Verb {
	return []Verb{
		VerbApprove,
		VerbDeny,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Verb) MarshalText() ([]byte, error) {
	switch s {
	case VerbApprove:
		return []byte(s), nil
	case VerbDeny:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Verb) UnmarshalText(data []byte) error {
	switch Verb(data) {
	case VerbApprove:
		*s = VerbApprove
		return nil
	case VerbDeny:
		*s = VerbDeny
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
