// Code generated by ogen, DO NOT EDIT.

package api

import (
	"mime"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

func (s *Server) decodeRegisterRequest(r *http.Request) (
	req *RegisterReq,
	rawBody []byte,
	close func() error,
	rerr error,
) {
	var closers []func() error
	close = func() error {
		var merr error
		// Close in reverse order, to match defer behavior.
		for i := len(closers) - 1; i >= 0; i-- {
			c := closers[i]
			merr = errors.Join(merr, c())
		}
		return merr
	}
	defer func() {
		if rerr != nil {
			rerr = errors.Join(rerr, close())
		}
	}()
	ct, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil {
		return req, rawBody, close, errors.Wrap(err, "parse media type")
	}
	switch {
	case ct == "application/x-www-form-urlencoded":
		if r.ContentLength == 0 {
			return req, rawBody, close, validate.ErrBodyRequired
		}
		form, err := ht.ParseForm(r)
		if err != nil {
			return req, rawBody, close, errors.Wrap(err, "parse form")
		}

		var request RegisterReq
		q := uri.NewQueryDecoder(form)
		{
			cfg := uri.QueryParameterDecodingConfig{
				Name:    "nonce",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.HasParam(cfg); err == nil {
				if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					request.Nonce = c
					return nil
				}); err != nil {
					return req, rawBody, close, errors.Wrap(err, "decode \"nonce\"")
				}
				if err := func() error {
					if err := (validate.String{
						MinLength:     0,
						MinLengthSet:  false,
						MaxLength:     128,
						MaxLengthSet:  true,
						Email:         false,
						Hostname:      false,
						Regex:         nil,
						MinNumeric:    0,
						MinNumericSet: false,
						MaxNumeric:    0,
						MaxNumericSet: false,
					}).Validate(string(request.Nonce)); err != nil {
						return errors.Wrap(err, "string")
					}
					return nil
				}(); err != nil {
					return req, rawBody, close, errors.Wrap(err, "validate")
				}
			} else {
				return req, rawBody, close, errors.Wrap(err, "query")
			}
		}
		{
			cfg := uri.QueryParameterDecodingConfig{
				Name:    "detail",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.HasParam(cfg); err == nil {
				if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
					var requestDotDetailVal string
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToString(val)
						if err != nil {
							return err
						}

						requestDotDetailVal = c
						return nil
					}(); err != nil {
						return err
					}
					request.Detail.SetTo(requestDotDetailVal)
					return nil
				}); err != nil {
					return req, rawBody, close, errors.Wrap(err, "decode \"detail\"")
				}
				if err := func() error {
					if value, ok := request.Detail.Get(); ok {
						if err := func() error {
							if err := (validate.String{
								MinLength:     0,
								MinLengthSet:  false,
								MaxLength:     512,
								MaxLengthSet:  true,
								Email:         false,
								Hostname:      false,
								Regex:         nil,
								MinNumeric:    0,
								MinNumericSet: false,
								MaxNumeric:    0,
								MaxNumericSet: false,
							}).Validate(string(value)); err != nil {
								return errors.Wrap(err, "string")
							}
							return nil
						}(); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return req, rawBody, close, errors.Wrap(err, "validate")
				}
			}
		}
		return &request, rawBody, close, nil
	default:
		return req, rawBody, close, validate.InvalidContentType(ct)
	}
}
