// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetHealthzOperation OperationName = "GetHealthz"
	RegisterOperation   OperationName = "Register"
	TapOperation        OperationName = "Tap"
	TapConfirmOperation OperationName = "TapConfirm"
)
